name: JTL Insights Analysis & Upload

on:
  workflow_dispatch:
    inputs:
      jtl_file_path:
        description: "Path to JTL file (inside repo or runner workspace)"
        required: true
        default: "results/results.jtl"

jobs:
  analyze-insights:
    runs-on: ubuntu-latest

    steps:
    
      # 1. CHECKOUT REPOSITORY
      
      - name: Checkout Repo
        uses: actions/checkout@v4

   
      # 2. SETUP PYTHON
     
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

    
      # 3. INSTALL DEPENDENCIES
      
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      
      # 4. EXPORT GOOGLE API KEY
      
      - name: Set Gemini API Key
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

     
      # 5. RUN THE INSIGHT ANALYSIS
      
      - name: Run Insight Analytics Agent
        run: |
          python backend/insights.py \
            "${{ github.event.inputs.jtl_file_path }}" \
            > final_insights_output.json

      
      
      # 7. SAVE AS ACTIONS ARTIFACT (OPTIONAL)
      
      - name: Upload as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: insights-output
          path: final_insights_output.json
